config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#home'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'

  resources :blogs do
  	collection do
  		get :home
  		get :profile
  	end
  end

  resources :articles
  resources :users
  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	accepts_nested_attributes_for :comments
	
	default_scope -> { order(created_at: :desc) }
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :article
	validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :comments, dependent: :destroy

	attr_accessor :remember_token
	before_save :email_downcase

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 20 }
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }


	class << self
		def new_token
			SecureRandom.urlsafe_base64
		end

		def digest(string)
			cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
			BCrypt::Password.create(string, cost: cost)
		end
	end

	def authenticated?(attribute, token)
			digest = self.send("#{attribute}_digest")
			return false if digest.nil?
			BCrypt::Password.new(digest).is_password?(token)
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	private

	def email_downcase
		self.email = email.downcase
	end

end

app/controllers/application_controller.rb
#require "application_responder"

class ApplicationController < ActionController::Base

  #self.responder = ApplicationResponder
  #respond_to :js

  #protect_from_forgery with: :exception
  include SessionsHelper

  private
   
  def logged_in_user
  	unless logged_in?
  		store_location
  		flash[:dander] = "Please log in."
  		redirect_to login_url
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  	@articles = Article.all
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	if @article.save
  		@article.update_attributes(article_params)
  		flash[:success] = "Post new article successfully."
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
  	@article = Article.find(params[:id])
  end

  def update
  	@article = Article.find(params[:id])
    if @article.update(article_params)
      if !params[:comments].nil?
        @comment = @article.comments.create!(:message => params[:comments]['content'], :article_id => @article.id, :user_id => current_user.id)
        flash[:success] = "Article updated"
        redirect_to article_path(@article.id)
      else

      end
    else
      render 'edit'
    end
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end

  def destroy
  	Article.find(params[:id]).destroy
		flash[:success] = "Album deleted"
		redirect_to articles_path
  end

  private

  def article_params
  	params.permit(:title, :content, :picture, :message)
  end
end	

app/controllers/blogs_controller.rb
#require "application_responder"
class BlogsController < ApplicationController
	#respond_to :js
	def home
		@articles = Article.all
		#respond_with(@articles)
	end

	def profile
		
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		
	end

	def destroy
		@article = Comment.find(params[:id]).article
		Comment.find(params[:id]).destroy
		flash[:success] = "Comment deleted"
		redirect_to article_path(@article)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :current_user, only: [:new]

  def new
  		render 'new'
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
			params[:session][:remember_me] == '1' ? remember(user) : forget(user)
			redirect_to root_url
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	flash[:success] = "Log out successfully"
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
	before_action :correct_user, only: [:update]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
  	if @user.save
  		log_in(@user)
  		flash[:success] = "Log in successfully"
  		redirect_to root_url
  	else
  		render 'new'
  	end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
	end

	def show
		@user = User.find(params[:id])
	end

	def destroy
		
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif(user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in(user)
				@current_user = user
				
			end
		end
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end


	def log_out
		forget(current_user)	#have bug when calling current_user in 2 cases list is ‘Issue’ column of ‘delete a session’ below
		session.delete(:user_id)
		@current_user = nil
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class = "article">
	<div class = "title"><%= link_to "#{article.title}", article_path(id: article.id) %></div>
	<div class = "date"><%= article.created_at.to_date.to_s %></div>
	<div class = "content"><%= article.content %></div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		
	});
</script>

app/views/articles/edit.html.erb
<% provide(:title, "Edit Article") %>

<div class = "edit_article_page">
	<div class = "title">edit article</div>
	<div class = "col-md-8 col-md-offset-2">
		<%= form_for(@article) do |f| %>
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control" %>

				<%= f.label :content %>
				<%= f.text_area :content, class: "content form-control" %>

				<%= f.submit "Update Article", class: "btn btn-primary" %>
			<% end %>
		</div>
</div>

app/views/articles/index.html.erb
<% provide(:title, "Articles List") %>

<div class = "article_index_page">
	<% if @articles.any? %>
		<% @articles.each do |article| %>
			<div class = "content">
				<div class = "title item"><%= link_to "#{article.title}", article_path(id: article.id) %></div>
				<div class = "date item"><%= article.created_at.to_date.to_s %></div>
				<div class = "action item">
					<% if logged_in? %>
						<% if current_user.admin? %>
							<div class = "action_edit"><%= link_to "Edit", edit_article_url(article.id), class: "btn-small btn-success" %></div>
							<div class = "action_delete"><%= link_to "Delete", article_url(article.id), method: :delete, data: {confirm: "You sure?"}, class: "btn-small btn-danger" %></div>
						<% end %>
					<% end %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/articles/new.html.erb
<% provide(:title, "Post new article") %>

<div class = "new_article_page">
	<div class = "title">post today's article</div>
	<div class = "col-md-8 col-md-offset-2">
		<%= form_for(@article) do |f| %>
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>

			<%= f.label :content %>
			<%= f.text_area :content, class: "content form-control" %>

			<%= f.submit "Post", class: "btn btn-primary" %>
		<% end %>
	</div>

</div>

app/views/articles/show.html.erb
<% provide(:title, "#{@article.title} | Article") %>

<div class = "show_article_page">
	<div class = "title"><%= @article.title %></div>
	<div class = "content"><%= @article.content %></div>

	<div class = "comment">
		<% if @article.comments.any? %>
			<div class = "title">comments</div>
			<div class = "col-md-6 col-md-offset-3">	
				<%= render @comments %>
			</div>
		<% end %>
		
		<% if logged_in? %>
			<div class = "col-md-6 col-md-offset-3">	
				<%= form_for(@article, :url => article_path( @article ), :html => { :method => :patch }) do |f| %>
					<%= render 'shared/error_messages', object: f.object %>

					<div class = "comment_box"><%= f.label :message, "Leave your comment" %></div>
					<%= f.text_area :message, placeholder: "Leave Your Comments...", name: "comments[content]", class: "form-control" %>

					<%= f.submit "Post", class: "btn btn-primary" %>
				<% end %>
			</div>
		<% end %>
	</div>

</div>

app/views/blogs/home.html.erb
<% provide(:title, 'Home') %>

<div class = "home_page">
	
	<div class = "col-md-8 col-md-offset-2 articles">
		<% if @articles.any? %>
			<div class = "topic">articles</div>
				<%= render @articles %>
		<% end %>
	</div>

</div>

app/views/blogs/profile.html.erb
<% provide(:title, "My Profile") %>

<div class = "profile_page">
	<div class = "title">profile</div>
</div>

app/views/comments/_comment.html.erb
	<div class = "comment_info"><%= link_to comment.user.name, comment.user %></div>
	<div class = "comment_content"><%= comment.message %></div>
	<% if logged_in? %>
		<% if current_user.admin? %>
			<div class = "comment_delete"><%= link_to "Delete", comment_url(comment.id), method: :delete, data: {confirm: "You sure?"}, class: "btn-small btn-danger" %></div>
		<% elsif current_user == comment.user %>
			<div class = "comment_delete"><%= link_to "Delete", comment_url(comment.id), method: :delete, data: {confirm: "You sure?"}, class: "btn-small btn-danger" %></div>
		<% end %>
	<% end %>

app/views/layouts/_footer.html.erb
<footer class = "footer">
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class = "header">
  		<div class = "nav_list">
          <% if logged_in? %>
            <div class = "item dropdown">
              <% if current_user.admin? %>
                <a href="#" class = "dropdown-toggle" data-toggle = "dropdown">Frank!</a>
              <% else %>
                <a href="#" class = "dropdown-toggle" data-toggle = "dropdown">Account</a>
              <% end %>
              <div class = "down_list dropdown-menu">
                <div class = "stack_item"><%= link_to "My Profile", profile_blogs_path %></div>
                <div class = "stack_item"><%= link_to "Log out", logout_path %></div>
              </div>
            </div>
          <% else %>
            <div class = "item"><%= link_to "Log in", login_path %></div>
          <% end %> 
        <div class = "item"><%= link_to "Home", root_url %></div>
        <div class = "item"><%= link_to "Article List", articles_path %></div>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <div class = "item"><%= link_to "Post", new_article_path %></div>
          <% end %>
        <% end %>
  			<div class = "item dropdown">
  				<a href="#" class = "dropdown-toggle" data-toggle = "dropdown">About C.C.Fang</a>
  				<div class = "down_list dropdown-menu">
  					<div class = "stack_item"><%= link_to "Profile", profile_blogs_path %></div>
            <div class = "stack_item"><%= link_to "Github", 'https://github.com/nbafrank72000' %></div>
  					<div class = "stack_item"><%= link_to "Contact", 'mailto:nbafrank72000@gmail.com' %></div>
  				</div>
  			</div>

			</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <% flash.each do |message_type, message| %>
	     <div id = "notice_wrapper">
	       <div class = "notice-<%= message_type %>"><%= message %></div>
	     </div>
	   <% end %>

    <%= render 'layouts/header' %>
    <%= yield %>
   

    <script type="text/javascript">
      $(document).ready(function(){
        setTimeout(function(){
          $('#notice_wrapper').fadeOut("slow", function(){
            $(this).remove();
          })
        }, 2500);
      });
    </script>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class = "error_explanation">
		<div class = "alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class = "sign_up_page">
	<div class = "logo">Burst</div>
	<div class = "title">Sign Up</div>

	<div class = "row">
		<div class = "col-md-6 col-md-offset-3">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :email %>
				<%= f.email_field :email, class: 'form-control', placeholder: "......@......" %>

				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control', placeholder: "At least 6 letters" %>

				<%= f.label :password_confirmation, "Repeat Password" %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>

				<%= f.submit "Create my account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>